name: Build

permissions:
  contents: write

on:
    push:
        tags:
          - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6.0.1
              with:
                ref: ${{ github.ref }}
            - name: Set up Python
              uses: actions/setup-python@v6.1.0
              with:
                python-version: '3.14'
            - name: Bundle
              run: python ./build/build.py
            - name: Get Title
              id: taginfo
              run: |
                TAG=${GITHUB_REF#refs/tags/}
                MSG=$(git tag -l "$TAG" -n99999)
                MSG=${MSG#*$TAG }
                echo "tag=$TAG" >> $GITHUB_OUTPUT
                echo "msg<<EOF" >> $GITHUB_OUTPUT
                echo "$MSG" >> $GITHUB_OUTPUT
                echo "EOF" >> $GITHUB_OUTPUT
                echo "message: $MSG, tag: $TAG"
            - name: Create a Release
              uses: actions/create-release@v1.1.4
              id: create_release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ steps.taginfo.outputs.tag }}
                release_name: Release ${{ steps.taginfo.outputs.tag }}
                body: ${{ steps.taginfo.outputs.msg }}
                draft: false
                prerelease: false
            - name: Upload Release Files
              id: upload-release-asset
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./dist/FissionReactorController.zip
                asset_name: FissionReactorController.zip
                asset_content_type: application/zip
